-- =============================================================================
-- V2: Core Tables - Tenants, Users, Roles, Permissions
-- =============================================================================
-- Foundation tables for multi-tenant authentication and authorization.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Permissions table
-- -----------------------------------------------------------------------------
CREATE TABLE public.permission (
    permission_id integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    name character varying(255),
    updated_at timestamp(6) without time zone
);

ALTER TABLE public.permission OWNER TO cognitia;

ALTER TABLE public.permission ALTER COLUMN permission_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permission_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.permission
    ADD CONSTRAINT permission_pkey PRIMARY KEY (permission_id);

-- -----------------------------------------------------------------------------
-- Roles table (tenant-scoped)
-- -----------------------------------------------------------------------------
CREATE TABLE public.roles (
    role_id integer NOT NULL,
    tenant_id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    role_name character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone
);

ALTER TABLE public.roles OWNER TO cognitia;

ALTER TABLE public.roles ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (role_id);

-- -----------------------------------------------------------------------------
-- Role-Permission junction table
-- -----------------------------------------------------------------------------
CREATE TABLE public.role_permisson (
    role_id integer NOT NULL,
    permission_id integer NOT NULL
);

ALTER TABLE public.role_permisson OWNER TO cognitia;

ALTER TABLE ONLY public.role_permisson
    ADD CONSTRAINT role_permisson_pkey PRIMARY KEY (role_id, permission_id);

ALTER TABLE ONLY public.role_permisson
    ADD CONSTRAINT fk31anmxm6uokr05wvalempoqsy FOREIGN KEY (permission_id) REFERENCES public.permission(permission_id);

ALTER TABLE ONLY public.role_permisson
    ADD CONSTRAINT fkm4sb5ufdrjv8sckuwr68uscu9 FOREIGN KEY (role_id) REFERENCES public.roles(role_id);

-- -----------------------------------------------------------------------------
-- Tenants table
-- -----------------------------------------------------------------------------
CREATE TABLE public.tenants (
    id uuid NOT NULL,
    about character varying(255),
    contact_email character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    domain character varying(255),
    name character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    root_user_id uuid
);

ALTER TABLE public.tenants OWNER TO cognitia;

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT tenants_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT ukh8eolq2o5fmgxjfnvbq1s2awt UNIQUE (contact_email);

-- -----------------------------------------------------------------------------
-- Users table
-- -----------------------------------------------------------------------------
CREATE TABLE public.users (
    id uuid NOT NULL,
    tenant_id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255),
    name character varying(255),
    password character varying(255),
    phone_number character varying(255),
    updated_at timestamp(6) without time zone,
    role integer
);

ALTER TABLE public.users OWNER TO cognitia;

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk9q63snka3mdh91as4io72espi UNIQUE (phone_number);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk21hn1a5ja1tve7ae02fnn4cld FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk4c6vlshk8x83ifeoggi3exg3k FOREIGN KEY (role) REFERENCES public.roles(role_id);

-- Add root_user_id FK constraint to tenants (circular reference resolved)
ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT uk524yup2kwlo68bd223ekf498r UNIQUE (root_user_id);

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT fkndtm2mkpsnwd5qqlu2tah9m5x FOREIGN KEY (root_user_id) REFERENCES public.users(id);

-- -----------------------------------------------------------------------------
-- Refresh tokens for JWT auth
-- -----------------------------------------------------------------------------
CREATE TABLE public.refresh_token (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    expires_at timestamp(6) without time zone,
    last_used_at timestamp(6) without time zone,
    replaced_by uuid,
    revoked boolean,
    token_hash character varying(255),
    updated_at timestamp(6) without time zone,
    user_agent character varying(255),
    user_id uuid NOT NULL
);

ALTER TABLE public.refresh_token OWNER TO cognitia;

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT fkjtx87i0jvq2svedphegvdwcuy FOREIGN KEY (user_id) REFERENCES public.users(id);

